### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ziguirifow** [Devlix/vQueue#11]
Error:  bad argument #2 to `format' (string expected, got nil)
File: Interface\AddOns\vQueue\vQueue.lua
Line: 171
Count: 1

**Comment by feljx** [comment]
Open "vQueue.lua" in your vQueue addon folder.
Go to line 171 (open with some kind of editor that shows line numbers).

Replace this

`self.hooks[frame].AddMessage(frame, string.format("%s", text), r, g, b, id)`

by this

`if text then`
`        self.hooks[frame].AddMessage(frame, string.format("%s", text), r, g, b, id)`
`end`
